### ISSUE TITLE
change group membership of contacts

### ISSUE THREAD

**Issue by sahne123** [libasys/contactsplus#10]
Is it possible to change group membership of contacts. I know adding via drag 'n drop is possible. But how to delete a membership?

drag 'n drop to 'nicht gruppiert' add's another group named 'none'.

**Comment by libasys** [comment]
next commit on master that issue is fixed!

**Comment by Visual-Notes** [comment]
Please tell me, how would i do that in version 1.0.4?

**Comment by libasys** [comment]
in current master you have to click on the trash icon and here you can choose, delete contact or delete all groups from contact! in version 1.0.5 batch delete is possible!
