### ISSUE TITLE
Deleting Groups

### ISSUE THREAD

**Issue by sahne123** [libasys/contactsplus#11]
I'm not sure if this works as supposed.

What i did: got some contacts in group A. Deleted Group A. The Group was no longer displayed in the sidebar, but the contacts keept their membership to Group A.

If this is how it should be i expected to see Group A again after hitting the "refresh Groups" Button. But it didn't.

**Comment by Visual-Notes** [comment]
I'm seeing the same in version 1.0.4. After deleting a group, members keep being assigned to that group, although the group doesn't exist anymore.
(ownCloud 8.1)

**Comment by libasys** [comment]
in current master 1.0.5 fixed!
