### ISSUE TITLE
birthday calendar - wrong age of contact

### ISSUE THREAD

**Issue by imago-maeror** [libasys/contactsplus#116]
Hi there!

I experience some strange behaviour with the contacts birthdays. I have set dates for birthdays of my contacts in contacts plus app as usual. I checked the dates of the year of birth a few times for different contacts but for some contacts the calculation of the age is incorrect. Without any identifiable issue the age differs by one year that is missing. 

For example one contact is born in the year 1949. The day of birth is set up correctly in the address book to 1949. So the actual age of this contact which is shown in the calendar should be (66). For some reason for this contact the age is shown correctly.
Another contact is born in 1985. Same here, there is the correct date in the address book. Here the age shown in calendar is (29).

By looking deeper into this issue i assume that the problem only occurs if the contacts birthday is in the future. Birthdays that are today or in the past appear to be correct.

Strange behaviour anyway.
##

**Comment by Pantek59** [comment]
I can confirm this bug, however here the birthdays in the past are wrong, too. :)
