### ISSUE TITLE
Add Federated Cloud ID to contacts app

### ISSUE THREAD

**Issue by schiessle** [libasys/contactsplus#13]
Would be nice if the contacts+ app could also handle the federated cloud ID. I tried to port my PR from here https://github.com/owncloud/contacts/pull/924 over to contacts+ but it seems not to easy.

**Comment by libasys** [comment]
Hello @schiesbn thanks for the hint, this will integrated, too! But at the moment i rewrite the calendar+ app to become the official calendar app! After this is finished i rewrite contacts+ app to become official contacts app! with federated cloud id, contactsmanager, search and so on!

**Comment by schiessle** [comment]
@libasys That's awesome. I'm really looking forward to it! Just saw that it isn't there yet and wanted to leave a issue so that it is not forgotten :)

**Comment by libasys** [comment]
perfect and many thanks!

**Comment by libasys** [comment]
comes with next commit on master! i think tommorow, if nothing happens!

**Comment by libasys** [comment]
is integrated!
