### ISSUE TITLE
»No Cards found!« empty content message is useless

### ISSUE THREAD

**Issue by jancborchardt** [libasys/contactsplus#17]
When there’s no contacts in the app, the very unhelpful and technical message

> No Cards found!

shows up. No one knows that »card« means »contact«. Compare that to the helpful message in the current app, offering two means of starting out with the app:

![capture du 2015-08-11 22-31-34](https://cloud.githubusercontent.com/assets/925062/9209828/dba5b98e-4078-11e5-86de-e627e90c474e.png)
Best do it similarly. :)

**Comment by libasys** [comment]
changed for empty addressbook, thanks for the tip
