### ISSUE TITLE
Adding contacts to groups adds a '\' to each group in backend

### ISSUE THREAD

**Issue by efelon** [libasys/contactsplus#2]
Seen in exported vcf, and sync via carddav.

Example from exported vcf file:
Before

> CATEGORIES:Cat1

After

> CATEGORIES:Cat1\,Cat2

This let's Androids contact app list a new Category when synchronizing via carddav:

> Cat1,Cat2

Removing the '\' manually in the database solves the issue. Both, Contacts+ and Android, still show the correct group memberships.

**Comment by libasys** [comment]
this is a escape mechanism, but i will investigate!

**Comment by libasys** [comment]
fixed in current version!
