### ISSUE TITLE
Problems with names/groups beginning <> A-Z (ICS Import errors)

### ISSUE THREAD

**Issue by deMattin** [libasys/contactsplus#26]
I had to import some contacts for another user of my cloudspace, because he had weird problems with contactsplus and there are following issues with importing contacts:
Names and groups have to **begin** with A-Z:
1. No Numbers allowed
2. no ÄÖÜ allowed
3. no other international characters allowed

This is an issue with importing AND if you generate this entries in calendarplus.
These entries are not only not shown (and so can't be deleted or modified) but further more can destroy the display of a complete categorie or other contacts.
5 "corrupt" of 27 contacts and 1 corrupt group had the result, that only 1 of the 27 contacts of the user has been shown!

Every UTF8-character has to be allowed in Names or Categories and the quick-jump A-Z on the right has to be enhanced with a # or something similar to group here all Characters not in A-Z.

I think, this is just a problem, that the readout of contacts and groups for displaying only recognizes A-Z and ignores anything beginning with another characters.

@libasys.
please have a look in your demo account.
I tried it there in the "test" adressbook as well and with one "Ärztlich" contact in group "Ärztlich" the complete adressbook "test" is destroyed (there are 4 contacts in)!
Only chance to repair it, is to delete or overwrite the calendar or to modify in Database!

**Comment by libasys** [comment]
I changed the behaviour with next version! Now the alphabet char get generates by contacts and not by a default alphabet array, so there is no problem with other languages!
On the demo is the new version for testing!

**Comment by deMattin** [comment]
Ah, this is great - I see it in demo and it works really nice.

Why don't you pull this in public git (in "rework" or a "developer" branch)?
In git it looks like you are actually not active working in the project but it seems, that you are much further in local development.
I think, if you pull also small steps to public git (not master), there is much more possibility for testing and community also sees development and progress.
And it's no problem, if it turns out, that something doesn't work perfect. And you have aditional people around that can do testing for you ... ;)

**Comment by libasys** [comment]
I have commited the new version to master! Please, can you test the new version and report bugs!
Thanks!

**Comment by deMattin** [comment]
Many Thanks. I will test it right now and post, if I find issues.
I already did some testing with you demo installation and by now, I found everything working ...
And as I see you are hard in development, I will retest actual master with some issues I found with my tests to switch over to contactsplus and calendarplus form official apps.

**Comment by deMattin** [comment]
Ok, actual master fixes the importing and display problems I described above and all 27 contacts and groups are displayed. Even signs like @, 0 or È or something like this are no problem any more.

So I state this issue as fixed in actual master. :+1: 

For the other ics importing and contacts problems I will open separate issues.

**Comment by deMattin** [comment]
Ok, I found one not very severe issue.
On the right the quick jump characters are dynamically generated but for a " " (space/blank) there is a jump mark generated, but you don't see it and it also doesn't work, if you click on it.
So if you ran in the actual import issue (#27), the contacts are sorted on top but have no useable "quick jump character" on the right.
Maybe a space can get as a grouping sign a UTF8 square symbol?
Not really a severe issue and not worth many hours of work but maybe you have a fast and simple fix for that.

**Comment by libasys** [comment]
this get fixed with the next version, coming soon!

**Comment by libasys** [comment]
in current master 1.0.5 fixed!
