### ISSUE TITLE
ICS import issue - sorting before first edit in calendarplus issue

### ISSUE THREAD

**Issue by deMattin** [libasys/contactsplus#27]
If you import ics files (exported from "official contacts") the contacts are all sorted by fullname (or firstname).
So a contact without firstname is sorted as if beginning with a blank " " and contacts with firstname and surname are sorted by firstname and not by surname.
If you open the contacts and save without editing, they are all sorted the "right" way as it is default in contactsplus.

Whatever this "open and save without changes" does with the data - it should be done already if you import the contacts.

**Comment by libasys** [comment]
fixed
