### ISSUE TITLE
Types of contact entry seems not to be compatible with ics standard (smartphone sync)

### ISSUE THREAD

**Issue by deMattin** [libasys/contactsplus#28]
If you import a contact, the TYPE flag of the imported data entries like "Arbeit", "Privat", ... are shown if you click on contact like they have been in ics data.
But if you edit contact, these Types are blank and you have to set them new.
![image](https://cloud.githubusercontent.com/assets/5565503/9424808/291bf258-48fa-11e5-968c-7cd1ed2727aa.png)
![image](https://cloud.githubusercontent.com/assets/5565503/9424809/46cb3a34-48fa-11e5-9fff-3ba19cd5f92a.png)

If you sync this new or reset types with a smartphone, the (some) types aren't recognized and shown as "sonstige", undefined or something like that.

The difference in ics (export from contactsplus before and after edit and save):
Before and also the content of originally imported ics from "official contacts":

``` BEGIN:VCARD
VERSION:3.0
PRODID:-//ownCloud//NONSGML Contacts 0.4.0.0//EN
N:Taxi Gelsen;;;;
UID:5f14bf76-d9bc-45b9-965a-efb3015999b3
REV:2015-08-15T11:27:36+00:00
FN: Taxi Gelsen
TEL;TYPE=WORK:0209 55 55 5
CATEGORIES:Sonstiges
END:VCARD
```

After edit and save in contactsplus:

``` BEGIN:VCARD
VERSION:3.0
PRODID:-//ownCloud//NONSGML Contacts 0.4.0.0//EN
N:Taxi Gelsen;;;;
UID:5f14bf76-d9bc-45b9-965a-efb3015999b3
REV:2015-08-22T16:19:49+00:00
FN:Taxi Gelsen 
CATEGORIES:Sonstiges
TEL;TYPE="WORK,VOICE":0209 55 55 5
END:VCARD
```

I see this difference in TYPE=WORK and TYPE="WORK,VOICE"
I don't have read the [rfc 2445](https://www.ietf.org/rfc/rfc2445.txt) but found some examples there looking like this **without double quotes**:

``` BEGIN:VCARD
   VERSION:3.0
   N:Stenerson;Derik
   FN:Derik Stenerson
   ORG:Microsoft Corporation
   ADR;TYPE=WORK,POSTAL,PARCEL:;;One Microsoft Way;
    Redmond;WA;98052-6399;USA
   TEL;TYPE=WORK,MSG:+1-425-936-5522
   TEL;TYPE=WORK,FAX:+1-425-936-7329
   EMAIL;TYPE=INTERNET:deriks@Microsoft.com
   END:VCARD
```

**Is is possible, that the double quotes after TYPE= are the problems cause?**
Is my sync app the problem?
Is my smartphone (Android 4.4 and 5) the problem?

And why doesn't calendarplus understand the TYPE=WORK in ics and doesn't set the type?
I will investigate further, but it's possible, that @libasys did already many research and is sure, he is right and if other apps (on smartphone) are the cause, it does not make sense to  fiddle this out.

**Comment by libasys** [comment]
nope all is correct for VCARD 3.0
one type no double quote, more then 1 type comma seperated and with double quoted!
