### ISSUE TITLE
Severe graphical issue editing contacts with more than 3 entries per type

### ISSUE THREAD

**Issue by deMattin** [libasys/contactsplus#29]
If you have a contact with many telephone numbers, only the first 3 entries for type of telephone number selector are displayed the right way in edit mode:
![1](https://cloud.githubusercontent.com/assets/5565503/9425201/cac81822-4907-11e5-8131-99d184a1f751.png)
If you select the following (4th and up) the pulldown seems to be in a layer behind and so these entries are not setable:
![2](https://cloud.githubusercontent.com/assets/5565503/9425205/fb876d5a-4907-11e5-9d4b-cfcb9774dcda.png)

Tested this in chrome and firefox with the same result.

**Comment by libasys** [comment]
fixed next commit on master! i think tommorow, if nothing happens!

**Comment by libasys** [comment]
fixed in current master and on appstore, complete new edit, new interface for better handling

**Comment by deMattin** [comment]
confirmed!
