### ISSUE TITLE
Sorting setting necessary (firstname, surname)

### ISSUE THREAD

**Issue by deMattin** [libasys/contactsplus#31]
Actual contactsplus only sorts by fullname.
It is essential to give the user the option to sort additional by firstname or surname and save the last used setting in account (like official app does).
Everybody has different usecases and sorting by fullname or company as it is default in contactsplus is a thing, noone will like for his friends.
As an example, I prefer sorting by firstname also in business if I have to decide for a sorting!

And it would be even great if you are able to set this depending on the calendar or even group so that you can set a sorting by surname for business and firstname for friends.
Here are many great things possible, that would be liked by users with bigger address books.

But the first approach should be a per account saved switching possibility that really every contacts app provides.
I see this switch as a really basic feature for a contacts app.

The actual sorting by fullname is a bit weird if you for example have a friend where you have filled in company but you will never search him with the beginning quick jump letter of his company because he is no business contact.

**Comment by libasys** [comment]
In the next version i add 2 new columns to the contacts table in the database (organization, bcompany)
With this addition it is possible to choose for every contact show as Company or show sure lastname!
The sorting for now comes from fullname if bcompany is true, if not it comes from lastname!
We working with apples "showas" labels, so if you use iphone,mac or ipad the same option get synced!

a first integration is on the demo http://demo81.libasyscloud.de

**Comment by libasys** [comment]
in current master 1.0.5 integrated!
