### ISSUE TITLE
Contacts+ not available on apps.owncloud.com

### ISSUE THREAD

**Issue by matzex** [libasys/contactsplus#32]
Unfortunately this app is not available on [apps.owncloud.com](https://apps.owncloud.com/usermanager/search.php?username=libasys&action=contents), is there any reason for this?
It would be nice to be able to update the app directly from my owncloud installation and this should be possible with the listing on apps.owncloud.com.

**Comment by libasys** [comment]
Version will soon be available! If all tests are good! So please test and Report issues here on github!

**Comment by matzex** [comment]
Okay, thank you.
