### ISSUE TITLE
thunderbird (SoGo) Sync failure

### ISSUE THREAD

**Issue by ghost** [libasys/contactsplus#38]
First of all i want to say thank you for this great App!
Unfortunately i am not able to sync Thunderbird  / SOGo 31.0.1 with my ownCloud 8.1.1.
Neither the carddav-url (https://www.c-rieger.de/owncloud/remote.php/contactsplus/) nor the contacs-url (https://www.c-rieger.de/owncloud/remote.php/contactsplus/addressbooks/user/contacts) works as expected. The sync of the contacts does not start/work.

If needed i could grant an access to my test-ownCloud, so you could be able to reproduce by your own?!

...::: Carsten

**Comment by ghost** [comment]
i found out that this error occurs as well on an existing ownCloud-User as on new once. 
I already tested disabling the standard contacts-app, but the error still occurs with this new contacts-plus-App.

**Comment by ghost** [comment]
ownCloud 8.1.1
PHP Version 5.6.10
MySQL Version 5.6.24

**Comment by ghost** [comment]
Ok, i got it.
Don't know why but i had to create a new thunderbird profile and that solved the issue.
Within the new profile all cards are in sync.

**Comment by criegerde** [comment]
Solved due to a new thunderbird profil
