### ISSUE TITLE
When trying to enable contacts+ via Owncloud admin backend: Error message 

### ISSUE THREAD

**Issue by farson2003** [libasys/contactsplus#39]
When trying to enable contacts+ via Owncloud admin backend: Error message appears: 

"App can't be installed because the version in info.xml/version is not the same as the version reported from the app store".

![contacts error](https://cloud.githubusercontent.com/assets/3358665/9575933/6a5f70be-4fcb-11e5-903d-769ce9a9a11d.png)

Enabling failed.

TO reproduce:
Owncloud 8.0.0 (updated to 8.0.1.).

**Comment by libasys** [comment]
changed version number on appstore to 1.0.3
