### ISSUE TITLE
Migrate Contacts from the Contacts App to Contacts+

### ISSUE THREAD

**Issue by dhuuk** [libasys/contactsplus#40]
Hey,

i installed Contacts+ but it says "No Contacts" the MySQL Tables are empty, is there any possibility to migrate the SQL tables from the "standard" contacts app to Contacts+?

**Comment by libasys** [comment]
you can export your contacts from the normal contacts app web interface and then per drag & drop import the .vcf file to contacts+ app!

**Comment by dhuuk** [comment]
normal contacts app is not working since the update to 8.1 if i enable it, the screen is just white. therefore i'd like to know how to migrate via mysql :)

**Comment by libasys** [comment]
the database scheme changed so it is not so easy via mysql! did you not sync contacts to your desktop or similar?

**Comment by dhuuk** [comment]
the sync does not work since the update to 8.1 so, no ... that's was the first problem. solving this i tried to migrate to contacts+ ;)

**Comment by ernesst** [comment]
When you import to contact+ don't forget to disable the contact app., to be sure to import your contact in contact+

**Comment by deMattin** [comment]
Drag and drop in opened calendar+ app is the safest way to import.
There's no need to deactivate official contacts app!

**Comment by ernesst** [comment]
I didn't know the drap'n drop.

I was uploading in a folder and clicking on the csv file. 
Thanks
