### ISSUE TITLE
Log flooded with errors "undefined index"

### ISSUE THREAD

**Issue by deMattin** [libasys/contactsplus#41]
After last update to 1.0.3 (rebase to master on git) my oc log is flooded with errors like:
`{"reqId":"HLCy21UIB2EPahSqjJN4","remoteAddr":"192.168.1.20","app":"PHP","message":"Undefined index: state at \/var\/www\/owncloud\/apps\/contactsplus\/lib\/app.php#1018","level":3,"time":"2015-08-31T18:20:33+02:00"}`
`{"reqId":"HLCy21UIB2EPahSqjJN4","remoteAddr":"192.168.1.20","app":"PHP","message":"Undefined index: country at \/var\/www\/owncloud\/apps\/contactsplus\/lib\/app.php#1018","level":3,"time":"2015-08-31T18:20:33+02:00"}`

Every address produces such a pair of errors, I think.
**There were so many errors, that my fail2ban locked me out!**
`The IP 192.168.1.20 has just been banned by Fail2Ban after
2 attempts against apache-overflows.`

My addresses have been imported from official contacts app a longer time ago.

Edit:
Sometimes there are also:
`{"reqId":"x7TaghGlpi19RHbzJe7w","remoteAddr":"192.168.1.20","app":"PHP","message":"Undefined index: postalcode at \/var\/www\/owncloud\/apps\/contactsplus\/lib\/app.php#1018","level":3,"time":"2015-08-31T19:28:53+02:00"}`

**Missing fields shouldn't throw out level 3 errors!
And also no single server requests -> fail2ban and server load problems!**

**Comment by libasys** [comment]
thanks for the bug report fixed in current master!

**Comment by deMattin** [comment]
The flooding is fixed, but there's something remaining.

If you call a contact with missing fields (imported contacts): there are error messages again.
So for opening a contact, this error messages also should be suppressed or get another log level.

Messages like this:

`{"reqId":"ELG8EAyFIh6dfOOQBXSY","remoteAddr":"192.168.1.20","app":"PHP","message":"Undefined index: work at \/var\/www\/owncloud\/apps\/contactsplus\/controller\/contactscontroller.php#1054","level":3,"time":"2015-08-31T20:34:55+02:00"}`

`{"reqId":"ELG8EAyFIh6dfOOQBXSY","remoteAddr":"192.168.1.20","app":"PHP","message":"Undefined index: home at \/var\/www\/owncloud\/apps\/contactsplus\/controller\/contactscontroller.php#1090","level":3,"time":"2015-08-31T20:34:55+02:00"}`

`{"reqId":"ELG8EAyFIh6dfOOQBXSY","remoteAddr":"192.168.1.20","app":"PHP","message":"Undefined index: cell at \/var\/www\/owncloud\/apps\/contactsplus\/controller\/contactscontroller.php#1090","level":3,"time":"2015-08-31T20:34:55+02:00"}`

`{"reqId":"qeu6rzv2QtRuleYxkGgY","remoteAddr":"192.168.1.20","app":"PHP","message":"Undefined index: type at \/var\/www\/owncloud\/apps\/contactsplus\/templates\/contact.show.php#95","level":3,"time":"2015-08-31T20:36:05+02:00"}`
...

**Comment by Forage** [comment]
I get loads of them too in 8.1.3. In my case it's:

```
{"reqId":"xcnyKrk4WE1Ve4CNDU21","remoteAddr":"192.168.1.1","app":"PHP","message":"Undefined index: Please double check the <a target=\"_blank\" href=\"%s\">installation guides \u2197<\/a>, and check for any errors or warnings in the <a href=\"#log-section\">log<\/a>. at \/usr\/share\/owncloud\/lib\/private\/l10n\/string.php#64","level":3,"time":"2015-09-30T18:13:42+00:00"}
{"reqId":"xcnyKrk4WE1Ve4CNDU21","remoteAddr":"192.168.1.1","app":"PHP","message":"Undefined index: Please double check the <a target=\"_blank\" href=\"%s\">installation guides \u2197<\/a>, and check for any errors or warnings in the <a href=\"#log-section\">log<\/a>. at \/usr\/share\/owncloud\/lib\/private\/l10n\/string.php#70","level":3,"time":"2015-09-30T18:13:42+00:00"}
```

Where it's constantly two lines (64 and 70) for each error in `string.php`

The message/index itself differs with some examples:
- `Show description \u2026`
- `Hide description \u2026`
- `Please double check the <a target=\"_blank\" href=\"%s\">installation guides \u2197<\/a>, and check for any errors or warnings in the <a href=\"#log-section\">log<\/a>.`
- `You don\u2019t have permission to upload or create files here`
- etc.
