### ISSUE TITLE
Collaborate with maps app

### ISSUE THREAD

**Issue by v1r0x** [libasys/contactsplus#43]
Really like the new contacts app!
The maps feature is cool, but I think it would be cooler to open the [maps app](https://github.com/owncloud/maps) (if installed and enabled) instead of another website.
Afaik there is currently no API to open the app at a specific location from within another app. But I think there was the idea to do so.

cc @Henni @jancborchardt @brantje @DJaeger

**Comment by jancborchardt** [comment]
Yup, would be a good enhancement if the Maps app is enabled. Please keep in mind to communicate via API and not private functions so this is not bound too specifically.

**Comment by libasys** [comment]
This can be happend with the contactsmanager! The map app only needs to integrate them like mail, calendar+, tasks+ it do! 
Example how easy it is!
https://github.com/libasys/calendarplus/blob/master/service/contactsintegration.php

**Comment by libasys** [comment]
Check it out, in the new version on the demo i integrated a map!

http://demo81.libasyscloud.de

**Comment by libasys** [comment]
in current master 1.0.5 integrated with his own map!
