### ISSUE TITLE
Display name = Organization

### ISSUE THREAD

**Issue by ernesst** [libasys/contactsplus#46]
I don't know if it's a bug, however i'm trying 
The "Display name" or the list layout displays the Organization and not the name + surname.

So for my my colleague I see the organization name + phone + email, so 15 rows with the same organization name but different phone and email.

Is it normal ?
Thanks

**Comment by libasys** [comment]
in the next version you have the choice to see a contact as firm or with sure+lastname

**Comment by libasys** [comment]
in current master 1.0.5 fixed!
