### ISSUE TITLE
Worng URl for reference

### ISSUE THREAD

**Issue by hitam4450** [libasys/contactsplus#48]
I just aupgraded to OC 8.1.2 and contact+ 1.0.4

Clicking on the URL of CardDav Sync Adressen (weitere Informationen) 
![contact](https://cloud.githubusercontent.com/assets/9738727/9633439/3da0c6f4-518d-11e5-8c56-8ae6e658e59f.png)

I just ended up with the help page of OC 7! 
![contact a](https://cloud.githubusercontent.com/assets/9738727/9633455/5645e306-518d-11e5-8d16-e736a806d818.png)

Is this correct and a requested feature???

regards, hitam4450

**Comment by libasys** [comment]
removed! thanks for the tip
