### ISSUE TITLE
Assigning  a contact to more then ONE Group

### ISSUE THREAD

**Issue by hitam4450** [libasys/contactsplus#50]
Hi,
I do have the case, that some of my contacts belong to (maybe 2 - or 3 ) different groups.

how to arrange for that in Contact+ 1.0.4??

regards, hiatm4450

**Comment by libasys** [comment]
per drag & drop! drag your contact to your favourite group and the contact is added to the group

**Comment by hitam4450** [comment]
Thank you for your advice! 
In Case i made a mistake, how to remove the contact from an additional group??

So far I could not find a way how to handle this issue! Thanks!

regards, hitam4450

**Comment by hitam4450** [comment]
If I drag and drop one contact over resp. to a cspecific group - all other groups getting highlighted (marked in red ) as well. This maybe getting  confusing, which group is really selected for assigning to the contact!

Hovering over one group, all other groups getting marked in red as well!

regards, hitam4450

**Comment by hitam4450** [comment]
Still OPEN issue!

**Comment by libasys** [comment]
Fixed!
