### ISSUE TITLE
Edit group Color (Description)

### ISSUE THREAD

**Issue by hitam4450** [libasys/contactsplus#51]
Hi, adding a group assigns automatically a color, so far so good!

However, how to change / edit the color of already defined group??

How to assign some additional information (text) to the group description?

regards, hitam4450

**Comment by libasys** [comment]
editing color group is not possible, color generated automatically by text length!

**Comment by hitam4450** [comment]
Very Strange reason and non-standard basis for choosing text color!

**Comment by libasys** [comment]
Isn't strange, the categories comes from core! Contacts+ works with the tagmanager of ownCloud and here is nö possibility to add a Color to a group! so this wont fix and be closed!
