### ISSUE TITLE
Renaming contact removes assigned group

### ISSUE THREAD

**Issue by astroneer** [libasys/contactsplus#53]
When editing (renaming) a contact which is assigned to multiple groups, the "non-active" group assignments are removed.
E.g.
- Contact is in group A, B and C
- Select group A
- Edit contact (e.g. change name)
- Save contact
- Contact is only assigned to group A (B and C were removed)
- The same applies for selecting another group (e.g. if group B was selected, the renaming removes groups A and C)

**Comment by libasys** [comment]
this is all fixed with next version

**Comment by astroneer** [comment]
Faster than lightning :-)
Thanks for all your effort

**Comment by libasys** [comment]
check the current demo, here are all the new features available, including a map to show your contacts on it! http://demo81.libasyscloud.de

**Comment by 1337sup3rh4x0r** [comment]
Once you go map, you never go back.

I can't switch back to list or card view after selecting map. Is it me or is this a bug? Using latest firefox.

**Comment by libasys** [comment]
you have to click the map button again to deactivate the map

**Comment by 1337sup3rh4x0r** [comment]
aaah! Thanks :)

**Comment by libasys** [comment]
in current master 1.0.5 fixed!

**Comment by astroneer** [comment]
Still not working in 1.0.5
:-(

**Comment by astroneer** [comment]
Works in 1.0.6.
Thanks :-)
