### ISSUE TITLE
Can' remove Contact Infos successfully

### ISSUE THREAD

**Issue by hitam4450** [libasys/contactsplus#54]
On my test contact i removed the company info, pressed Ok - and it still shows in the contact header!
Opening the contact - the company info ist still there and is not removed as requested!

Is this a feature or a bug??

regards, hitam4450

**Comment by libasys** [comment]
in current master 1.0.5 fixed!

**Comment by hitam4450** [comment]
I tried it this morning, the problem is still there -- NOT fixed!
