### ISSUE TITLE
Unasign Contacts from Group

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [libasys/contactsplus#56]
Hi,
I had a lot of groups that were no longer relevant in my contacts that I imported from google.
So I decided to delete all the groups via the "add group" dialog in the top of the app (quite confusing by the way that you have to click "add group" to delete one, but propably the same as having to click "Start" to select "shutdown" in Windows ;) ).
Still all Contacts have their groups assigned to them even though in the list on the left, they don't exist anymore.
How do I get rid of that?

**Comment by libasys** [comment]
batch feature in current master where you can remove all groups from selected contacts!

**Comment by 1337sup3rh4x0r** [comment]
Sounds good!
But how do I unassign a group from a contact in gereral? I couldn't find that function so far

**Comment by libasys** [comment]
click on the trash icon here you can choose delete contact or delete all groups from contact!

**Comment by hitam4450** [comment]
Well, that sounds nice -- however  the user expects to see a drop-down list - in that case, the contact is assigned to more then 1 group - the user will be able to choose the gruop tbe unassigned from the contact and is not pushed to delete all groups from the contact!

regads, hitam4450
