### ISSUE TITLE
Shared address book does not list groups

### ISSUE THREAD

**Issue by astroneer** [libasys/contactsplus#57]
A shared address book does not list the groups in the left area (only "all" and the "not grouped" groups are displayed). Reloading groups does not help.
However, all group icons are displayed on the right area behind the names (and the tooltips show the correct group names).

**Comment by libasys** [comment]
you have to add the groups by yourself!

**Comment by astroneer** [comment]
![shared_ab_missing_groups](https://cloud.githubusercontent.com/assets/14089226/9667217/e8690fe0-527a-11e5-8511-fd8a490a955e.jpg)
That's what I thought first as well (like in the classical contacts app).
But why are the groups displayed as icons on the right area behind the names?
This means that the groups are known but not used on the left panel...?!

**Comment by astroneer** [comment]
Update (version 1.0.5):
After "editing" a contact (open contact, no change necessary, clicking ok) the groups of this contact appear on the left panel (after clicking reload of groups). Repeating this for multiple contacts makes the group panel complete...

**Comment by libasys** [comment]
closed!
