### ISSUE TITLE
1.0.5 - Only 200 contacts are shown.

### ISSUE THREAD

**Issue by pravussum** [libasys/contactsplus#58]
On current master (fe7e4a32e3) only 200 of formerly 270+ contacts are shown ("All" list). Thus, one group remains emtpy and the single contact that was inside is missing.
It almost seems as if there was a limit on the db query but the 200 can be conincidence as well.
If you need more info, let me know - maybe you can point me in the right direction.
Sadly Firefox crashes on showing the content of the reply of the XHR request for getcontactcards.

**Comment by libasys** [comment]
can you more specify the problem!
Your enviroment, browser, operating system, what says the js error log of your browser, error log on admin settings?

**Comment by libasys** [comment]
Fixed in current master.

**Comment by pravussum** [comment]
Ah, cool, I'm just now typing my answer :-P

**Comment by pravussum** [comment]
Hm, sorry, but still not working on current master. Please reopen.

When loading the site, the "right" number of contacts displays for a short time right beside the name of the address book. Then, while further loading the site (content on the right side) it changes to 200. As already mentioned, looks like a limit or max somewhere.

The HTTP reply for getcontactcards (which Firefox crashes on showing) seems pretty large (505,74 KB) - could that be an issue?

I'm running owncloud on a Strato vServer with self-signed SSL certificate. Apache, Ubuntu 14.04 LTS 64bit.
Client side is Windows 7 and latest Firefox. 

Nothing in the server log.

In the JS console, there is a CSP error regarding image loading:
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf data:image/jpeg;base64 ...[base64 content left out]

And another CSP error:
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://[URL lef out] 'unsafe-eval'").

**Comment by libasys** [comment]
This is a csp Problem try this patch. Link is within the discussion: https://github.com/libasys/contactsplus/issues/45

**Comment by pravussum** [comment]
By the way... contacts where visible before I updated to latest master... sorry, but don't recall the version I had before...
But it doesn't seem to be an import problem like in your linked issue.

**Comment by pravussum** [comment]
CSP fix working, but obviously not related. Thanks anyway :-)

**Comment by libasys** [comment]
In this discussion at the and is a link how to fix the CSP (content security policy) problem to Display the pics of your contacts! Please test on my Demo http://demo81.libasyscloud.de to import your contacts! You can register an Account for testing, after Test you can delete your contacts! If here is also aProblem for displaying more than 200 contacts! On the Demo is the csp fix integrated.

**Comment by pravussum** [comment]
As I said, the CSP patch is fixing the image loading issue (just manually edited contentsecuritypolicy.php), but the contact count issue remains.

**Comment by libasys** [comment]
please test it on my Demo, if here also problems occurs with displaying more than 200 contacts!

**Comment by pravussum** [comment]
Worked on your server. After reimporting the whole addressbook on my server, worked as well. I think this was an upgrade issue.
