### ISSUE TITLE
photo upload not working

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [libasys/contactsplus#59]
drag and drop of pictures doesn't work, as well as choosing a local picture from file upload dialog.
picking a picture from owncloud storage works fine.
There is no log output.

**Comment by libasys** [comment]
please check add blocker, maybe problem of CSP (content security policy) browser!

**Comment by 1337sup3rh4x0r** [comment]
I deactivated AddBlockPlus and Ghostery for the Owncloud site but it's still not working.

**Comment by libasys** [comment]
Double Post please use this issue https://github.com/libasys/contactsplus/issues/45

**Comment by 1337sup3rh4x0r** [comment]
U sure this is the same issue? I already fixed the issue #45 with the fix in core that you mentioned there, but this issue here persists.
