### ISSUE TITLE
Number of contacts calculated wrong

### ISSUE THREAD

**Issue by sonst-was** [libasys/contactsplus#61]
Hi there,

I just synchronized my contacts with DAVdroid with Contacts+. It seems that Contacts+ has a problem calculating the number of total contacts.

I have 205 contacts in total in my addressbook (according to Android phone). Contacts+ sometimes shows that I have in deed 205 contacts, but sometimes it shows that I have only 80:

http://img.sonst-was.de/img/1441429694.png

**Comment by libasys** [comment]
Fixed current in master.
