### ISSUE TITLE
Bug: After clicking on World Map Icon, other Icons (Card/List view) have no effect.

### ISSUE THREAD

**Issue by farson2003** [libasys/contactsplus#62]
Bug: After clicking on World Map Icon, other Icons (Card/List view) have no effect.

**Comment by libasys** [comment]
this is not a bug, this is the default behaviour!

**Comment by farson2003** [comment]
@libasys 
maybe we are not talking about the same issue here.
Allow me to specify the steps to reproduce:
1.  Open https://ssl.webpack.de/demo81.libasyscloud.de/index.php/apps/contactsplus/
2.  You will see the List view of the contacts.
3. Click on "Card view". You will successfully see the card view.
4. Click back to list view. No problem.

Then:
5. Click on "Map view". Map shows successfully.
6. Click on "List view". NOTHING HAPPENS.
7. CLick on "Card view". NOTHING HAPPENS.

Why does your app not react anymore to the user's request to show the List or Card view in steps 6 or 7?

Are you sure this is a desired behaviour?

**Comment by libasys** [comment]
You are in the map view, one click again on the map button, deactivate the map view! if you read the tooltip of the world map button, it says click again and map view is deactivated and the green color of the map icon turns to normal black!

**Comment by farson2003** [comment]
@libasys 
You created a wonderful app.
Please allow more users to comment on that issue before closing. I strongly feel the GUI behaviour in these three buttons in these issue is incongruent.

**Comment by deMattin** [comment]
In my opinion it works fine like it is.
With the world map button you switch to a global map with all of your contacts and switching list/card view doesn't make sense there.

But GUI enhancements to make it more intuitive could be:
1. to hide the list/card view buttons if you are in global map view (without moving position of global map button!). This probably would make it more clear in GUI, that you are in map view and have to switch back, if you want to see a list of contacts.
or
2. to deactivate global map view, if you click either on list view or card view button and switch directly to the clicked view.
This is probably the most intuitive way and also has been my first try to go back to list, when I first activated global map.

**Comment by pravussum** [comment]
It's very counterintuitive like it is now. I was just about to open another issue until I found this one.
If you have 3 buttons beside each other representing 3 different views on the same data, one expects each button to switch to the corresponding view - not two buttons to switch the view and a third one to toggle another view. 
Either of the suggested solutions would be fine, but this has to be changed (I'd personally prefer 3 buttons switching between views).

**Comment by libasys** [comment]
changed behaviour in next commit!

**Comment by pravussum** [comment]
Very cool :+1: Confirmed working
