### ISSUE TITLE
Import 40 Contact but visible only 12 in-app

### ISSUE THREAD

**Issue by Hideio** [libasys/contactsplus#67]
I Import a vcf whit 40 contacts that i just exportet whit the standart contact app but contact+ only show 12 of them in-app. Syncing to my phone from contact+ whit Davdroid syncs all 40 , so nothing lost only 28 contacts not visible in-app. If i disable and re-enable the adressbook in the app only the counter change from 12 to 40. When i leave the contact app and come back the counter change also back to 12.

I use OC 8.1.1 & contact+ 1.0.6, standart contact was 0.4.0

**Comment by libasys** [comment]
is it possible to post a vcf file or send  the file to doell@libasyscloud.de?

**Comment by Hideio** [comment]
Im not so happy to provide my whole contacts to „the internet“ specaly for law reason of sensitive personal information, we are both from germany i hope you understand. But i copy the first four out of the export.vcf and change the privacy relatet thinks whit random patterns for example.

I make a second try and exported my contacts direkty from the phone and import it to contacts+ but same behavior, the contacts will count but not visible and davdroid give me an 402 error when it try to sync. After that i delete the whole addressbook inside your app and start to import the first export.vcf again, now its count 40 again but no one is visible.

Export.vcf from Ouwncloud Contact 0.4.0

BEGIN:VCARD
VERSION:3.0
PRODID:DAVdroid/0.7.6 (ez-vcard/0.9.6)
UID:0e1e86ed-99c0-42a3-aed1-890f8be6f0b9@omv.fritz.box
FN:Muster1
N:;Muster1;;;
TEL;TYPE=cell:+86123456
TEL;TYPE=cell:+86165432
TEL;TYPE=x-other:020995509302\,008615555
TEL;TYPE=cell:+86166666
TEL;TYPE=work:+85277777
TEL;TYPE=home:020995509306\,0086188888
TEL;TYPE=pref,pref:+852999999
TEL;TYPE=x-other:+86112121212
TEL;TYPE=x-hongkong:+8522323232
IMPP:x-apple:114545454
IMPP:x-apple:114545454
REV:2015-05-13T10:31:26+00:00
END:VCARD

BEGIN:VCARD
VERSION:3.0
PRODID:DAVdroid/0.6.12 (ez-vcard/0.9.6)
UID:22348106-8054-4b66-9ce7-1cdab9f33f4a@omv.fritz.box
FN:Muster2
N:;Muster2;;;
TEL;TYPE=cell:+49 171 898989
TEL;TYPE=work:+4989653453
TEL;TYPE=home,pref:089789789
EMAIL;TYPE=home:muster2@muster-mail.de
REV:2015-03-12T07:04:55+00:00
END:VCARD

BEGIN:VCARD
VERSION:3.0
PRODID:DAVdroid/0.8.4 (ez-vcard/0.9.6)
UID:6322f303-02e6-4uso-8c60-72a997e1226c@omv.fritz.box
FN:Muster3
N:;Muster3;;
TEL;TYPE=cell,pref:0049172321321
TEL;TYPE=cell:+491769245245
TEL;TYPE=home:0931564564
TEL;TYPE=x-muster3:+4917564564
TEL;TYPE=work:+49178676788
EMAIL;TYPE=home:muster3.muster3@gmx.de
NOTE:9999X12345
REV:2015-08-28T11:58:19+00:00
END:VCARD

BEGIN:VCARD
VERSION:3.0
PRODID:-//ownCloud//NONSGML Contacts 0.3.0.17//EN
N:;Muster4;;;
FN:Muster4
TEL;TYPE=OTHER:+4917423456
EMAIL;TYPE=HOME:muster4@hotmail.com
BDAY:1920-11-11
UID:2e90177e-xy43-84e9-b7e6-12320d7a0069@omv.fritz.box
REV:2014-09-22T15:26:39+00:00
END:VCARD

**Comment by libasys** [comment]
please test current master i added a fix for it, and gimme short feedback! Thanks

**Comment by srt10coupe** [comment]
i think is the same issue:

80 contacts on phone, 56 on contactsplus app

oC 8.1.2

after git pull --rebase origin master and sync same

20150906T170611Z V org.dmfs.syncadapter.SyncAdapter background data setting:   background data value:true
20150906T170611Z V org.dmfs.syncadapter.SyncAdapter network type: 1   newtork subtype: 0   is connected: true   is available: true
20150906T170611Z V org.dmfs.syncadapter.SyncAdapter starting sync ...
20150906T170611Z V org.dmfs.contacts.GroupManager performed group updates in: 29ms
20150906T170611Z V org.dmfs.carddav.syncadapter.SyncAdapter Syncing https://srt10coupe.de/owncloud/remote.php/contactsplus/addressbooks/admin/ockontakte/ admin
20150906T170615Z V org.dmfs.dav.methods.DavOptions Code : 200
20150906T170615Z I org.dmfs.dav.Dav enabling preemptive Authentication
20150906T170615Z V org.dmfs.contacts.ContactsManager time to update uids: 55 ms
20150906T170615Z I org.dmfs.carddav.syncadapter.SyncAdapter no changes on remote address book, faking sync-collection
20150906T170615Z V org.dmfs.sync.Synchronator pairing entities
20150906T170615Z V org.dmfs.sync.Synchronator sorting 80 pairs
20150906T170615Z I org.dmfs.sync.Synchronator r/u/n: 0/0/0
20150906T170615Z V org.dmfs.sync.Synchronator conflicts: 0
20150906T170616Z V org.dmfs.contacts.GroupManager trigger memberships
20150906T170616Z I org.dmfs.carddav.syncadapter.SyncAdapter storing synctoken: 1440675646
20150906T170616Z I org.dmfs.syncadapter.SyncAdapter sync complete

App: org.dmfs.carddav.Sync
App version: 0.4.14
OS version: 22
OS Info: oneplus/bacon/A0001:5.1.1/LMY48B/YOG4PAS1N0:user/release-keys
Manufacturer: OnePlus
Date: Sun Sep 06 19:06:21 MESZ 2015

**Comment by Hideio** [comment]
Your fix solved the problem for me, after update the app and import vcf agian every contact is visible now. Thank you for the quick fix.
