### ISSUE TITLE
Distorted Layout in 1.0.6

### ISSUE THREAD

**Issue by hitam4450** [libasys/contactsplus#68]
Hi, I updated contacts+ to 1.0.6 and I think it got worse then better!
Before the update the number of members of a group shown in the same line as the group name!
Now it shows in a separate line! Is this a feature or a bug???

![oc812h](https://cloud.githubusercontent.com/assets/9738727/9703566/7deb1040-5488-11e5-9422-1a1d74711c82.png)

I try to imagine, if I will finally import my 800+ contacts, nicely organized in 40+ groups!
With the enclosed layout, they will never fit on the largest screen available all at once!
regards, hitam4450

**Comment by libasys** [comment]
should not, please give me some more information about your environment and OS and which browser do you use! I use FF on Mac and all is well!

**Comment by hitam4450** [comment]
UBUNTU 14.04 LTS, with FF 40.0.3

**Comment by libasys** [comment]
Have you the same layout problems on the demo http://demo81.libasyscloud.de ? if not, then please clear the cache of your browser!

**Comment by hitam4450** [comment]
no problems with layout in the demo!

**Comment by hitam4450** [comment]
i cleared the cache, problem is still available! No Change!

**Comment by libasys** [comment]
have you a demo account for me to look for?

**Comment by hitam4450** [comment]
I opened the contacts+ app in a new window ----> no change!

No, i do not have demo account! Sorry!

**Comment by hitam4450** [comment]
What I noticed, zooming in and out changes the format and layout!
Sometimes the layout is OK, sometimes as described!
Maybe that helps!

**Comment by hitam4450** [comment]
The smaller the view, the layout gets scrambled!

**Comment by libasys** [comment]
change this line https://github.com/libasys/contactsplus/blob/master/css/style.css#L508
to 

```
width:130px;
```

Should solve your problem!

**Comment by hitam4450** [comment]
Ok, fixed. It solved the software problem - not mine! It works fine now!
