### ISSUE TITLE
Multiple groups of a contact create a combined group

### ISSUE THREAD

**Issue by astroneer** [libasys/contactsplus#72]
Assigning multiple groups in the web browser works fine.
However, when multiple groups (e.g. group1, group2, group3) are assigned to contacts my android addressbook shows one group named "group1,group2,group3" instead of listing the 3 groups as 3 categories.
Checking the calendar plus addressbook export shows:
CATEGORIES:Group1\,Group2\,Group3
I would expect (as seen in other apps) no backslash:
CATEGORIES:Group1,Group2,Group3
I guess the sync via dav is sending this "\," version in the vcard to my mobile and the "\," connects the 3 groups to one single group name.
Probably there should be no \ between categories in vcards ?!

**Comment by libasys** [comment]
Please read all existing issues! https://github.com/libasys/contactsplus/issues/2

**Comment by astroneer** [comment]
Sorry... I know it sucks when people raise duplicated stuff... :-(
