### ISSUE TITLE
Photo upload for contacts not possible because of exif_read_data()

### ISSUE THREAD

**Issue by reaseno** [libasys/contactsplus#73]
I tried to add photos to contacts, but its nothing done with no message.
But I get this message in the log:

{"reqId":"F\/MfOhE4QIr3kk9qRvn6","remoteAddr":"","app":"PHP","message":"Call to undefined function OCA\ContactsPlus\Controller\exif_read_data() at \/u\/www\/REMOVED\/htdocs\/owncloud\/apps\/contactsplus\/controller\/photocontroller.php#243","level":3,"time":"2015-09-09T23:41:26+00:00"}

Why is exif needed just for contact pictures? Nevertheless I can't install modules on the used server, as I have no permissions and probably the server admins won't install it.

OC: 8.1.2.1
openSUSE 13.1
ContactsPlus: 1.1.0

**Comment by libasys** [comment]
thanks for the bug report! i will investigate and coding a fallback!

**Comment by reaseno** [comment]
Very good. Thank you :+1:

**Comment by libasys** [comment]
fixed
