### ISSUE TITLE
carddav syncing issue

### ISSUE THREAD

**Issue by mdik** [libasys/contactsplus#75]
Hi,

ContactsPlus has the same problem as Contacts which is solved by https://github.com/owncloud/contacts/pull/987/files

The corresponding file for contactsplus is ./lib/connector/sabre/carddav/addressbook.php

Sincerely,

Malte

**Comment by libasys** [comment]
This fix can't work, the method must implemented in the backend.php, too! https://github.com/owncloud/contacts/blob/master/lib/carddav/backend.php

**Comment by mdik** [comment]
But it worked.

**Comment by libasys** [comment]
should be fixed in current version!

**Comment by mdik** [comment]
It is. Thank you!
