### ISSUE TITLE
Contactsplus not importing contacts

### ISSUE THREAD

**Issue by Connor0308** [libasys/contactsplus#76]
### Steps to reproduce
1. Import a .vcf file
### Expected behaviour

Contacts should be imported and show up in the app.
### Actual behaviour

The app appears in the webinterface, but when trying to import my contacts from a .vcf file (either by drag and drop or by uploading the file to the file app and opening it), an import dialogue opens and a progress bar is going up to a 100%. After that, another window opens saying "importing contacts", but this stays at 0%. Funnily, the standard contact app is working (tried it and uninstalled it afterwards).
The app shows the number of contacts right to the name of the addressbook, but no contact is shown in the main window.
### Server configuration

**Operating system**:
Shared Server 

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.4.40

**ownCloud version:** (see ownCloud admin page)
8.1.2

**Updated from an older ownCloud or fresh install:**
Updated from 8.1.0

**List of activated apps:**

Enabled:
- activity: 2.0.2
- bookmarks: 0.4
- calendarplus: 1.0.8
- contactsplus: 1.0.7
- direct_menu: 0.3
- encryption: 1.0.0
- files: 1.1.10
- files_external: 0.2.3
- files_locking:
- files_mv: 0.8.1a
- files_pdfviewer: 0.7
- files_sharing: 0.6.2
- files_texteditor: 0.4
- files_trashbin: 0.6.3
- files_versions: 1.0.6
- files_videoviewer: 0.1.3
- firstrunwizard: 1.1
- galleryplus: 13.0.0
- logreader: 1.0.0
- music: 0.3.7
- ownnote: 1.05
- provisioning_api: 0.2
- tasksplus: 1.0.2
- templateeditor: 0.1
- updater: 0.6
- weather: 1.2.0
  Disabled:
- external
- gallery
- user_external
- user_ldap
- user_webdavauth

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'ocfkqxp5cequ',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    0 => 'Domain1',
  ),
  'datadirectory' => '/home/XXXX/ownclouddata',
  'overwrite.cli.url' => 'http://URL',
  'dbtype' => 'mysql',
  'version' => '8.1.2.1',
  'dbname' => 'dbname',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'user',
  'dbpassword' => 'secret',
  'logtimezone' => 'UTC',
  'installed' => true,
  'appstore.experimental.enabled' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'ssl',
  'mail_from_address' => 'p.deubner',
  'mail_domain' => 'mail.de',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => '',
  'mail_smtpport' => '465',
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'loglevel' => 0,
  'theme' => '',
  'maintenance' => false,
  'log_rotate_size' => 104857600,
  'forcessl' => true,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:**
Google Chrome, Microsoft Edge

**Operating system:**
Windows 10
#### Web server error log

none
#### ownCloud log (data/owncloud.log)

webdav Exception: {"Message":"HTTP\/1.1 503 Exception: App not installed: contacts","Code":0,"Trace":"#0 [internal function]: {closure}(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#1 \/home\/deubnero\/public_html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\n#2 \/home\/deubnero\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\Event\EventEmitter->emit('beforeMethod', Array)\n#3 \/home\/deubnero\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#4 \/home\/deubnero\/public_html\/remote.php(64): Sabre\DAV\Server->exec()\n#5 \/home\/deubnero\/public_html\/remote.php(135): handleException(Object(Exception))\n#6 {main}","File":"\/home\/deubnero\/public_html\/remote.php","Line":62}  
webdav Exception: {"Message":"HTTP\/1.1 503 Exception: App not installed: contacts","Code":0,"Trace":"#0 [internal function]: {closure}(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#1 \/home\/deubnero\/public_html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\n#2 \/home\/deubnero\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\Event\EventEmitter->emit('beforeMethod', Array)\n#3 \/home\/deubnero\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#4 \/home\/deubnero\/public_html\/remote.php(64): Sabre\DAV\Server->exec()\n#5 \/home\/deubnero\/public_html\/remote.php(135): handleException(Object(Exception))\n#6 {main}","File":"\/home\/deubnero\/public_html\/remote.php","Line":62}  
carddav Exception: {"Message":"HTTP\/1.1 403 Permission denied to create file (filename 8A514641-4335-8005-5487-B892A3B6DA69.vcf)","Code":0,"Trace":"#0 \/home\/deubnero\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1053): Sabre\DAV\Collection->createFile('8A514641-4335-8...', Resource id #386)\n#1 \/home\/deubnero\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\DAV\Server->createFile('8A514641-4335-8...', Resource id #386, NULL)\n#2 [internal function]: Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#3 \/home\/deubnero\/public_html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/home\/deubnero\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\Event\EventEmitter->emit('method:PUT', Array)\n#5 \/home\/deubnero\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#6 \/home\/deubnero\/public_html\/apps\/contactsplus\/appinfo\/remote.php(66): Sabre\DAV\Server->exec()\n#7 \/home\/deubnero\/public_html\/remote.php(132): require_once('\/home\/deubnero\/...')\n#8 {main}","File":"\/home\/deubnero\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Collection.php","Line":91}

**Comment by libasys** [comment]
Have you had looked in the Database on the table conplus_contacts? Are here your contacts listed? But it could be a Problem of encryption, too! You have an 403 error permission denied! Maybe missing rights!

**Comment by Connor0308** [comment]
Good morning,

thank you for your reply. I checked the rights ans ownership via commandline. They are the same with working plugins, so I can't see any issue here.
In the database, there is no table conplus_contacts - I have three tables called
oc_conplus_addressbook, oc_conplus_properties and oc_conplus_cards.
As far as I can judge, only the oc_conplus_properties has entries.

-----Original Message-----

**Comment by Connor0308** [comment]
I have to correct myself. The table oc_conplus_cards holds the correct number of contacts.

**Comment by libasys** [comment]
have you a demo account for me?

**Comment by Connor0308** [comment]
Try to use "demo" both for user and password at https://deubner.owncube.com.

**Comment by libasys** [comment]
i have no problems to import contacts! all contacts listed! how many contacts contains your vcard do wanted to import? can you paste one or two of them? have you tested current master of contacts+?

**Comment by Connor0308** [comment]
That's really odd. I'm on version 1.0.7 and haven'ttried any other version so far. 
The vCard contains 268 contacts - not that much...
I have to leave now and will get back this evening.
Thanks for your support so far!

**Comment by Connor0308** [comment]
Well, this evening became a little later...
Putting it all together, it must have been some kind of misconfiguration.
After a clean installation and after building the vcf-cards right (meaning after the standard), it works flawless now.
Thanks for your help!
