### ISSUE TITLE
mobile / respsonsive layout messed up 

### ISSUE THREAD

**Issue by sahne123** [libasys/contactsplus#9]
![2015-07-16 12_30_49-kontakte - owncloud](https://cloud.githubusercontent.com/assets/1149152/8720921/5eb452d6-2bb6-11e5-8ffb-ee85a4ed4c43.png)

**Comment by jancborchardt** [comment]
Clearly we have to reduce the amount of buttons there.
- search should use the global search field which will show in the blue header bar. That’s properly responsive
- the button to add a contact should be the first button in the left sidebar, no need to show it there all the time
- what does the »Organization« dropdown do?
- leaves just the view toggle. That can stay, or even move to the bottom left settings

What do you think @libasys @schiesbn @MorrisJobke?

**Comment by sahne123** [comment]
The »Organization« Dropdown is part of the search. I agree using the global Search field would be a good way. Not sure how important it is to search in specific properties of contacts. For me it would be fine to search always in all Properties.

I also agree with your other thoughts. :+1:

**Comment by libasys** [comment]
in current master 1.0.5 fixed!
